### ISSUE TITLE
A couple of bugs I noticed in your convert-nemo.py script

### ISSUE THREAD

**Issue by fairydreaming** [FailSpy/export-nemo-to-safetensors#1]
1. Mapping of `mlp.linear_fc1.layer_norm` weight and bias tensors seems to be reversed (bias mapped to weight and vice versa) in this place:

https://github.com/FailSpy/export-nemo-to-safetensors/blob/e37ce3a403627c4332840ec139e94874c5fc1099/convert-nemo.py#L13-L14

2. This is minor issue, but .safetensors extension is missing from the last file name (in two places) here:

https://github.com/FailSpy/export-nemo-to-safetensors/blob/e37ce3a403627c4332840ec139e94874c5fc1099/convert-nemo.py#L70-L72

3. There is a typo here (should be `sharded_state_dict`):

https://github.com/FailSpy/export-nemo-to-safetensors/blob/e37ce3a403627c4332840ec139e94874c5fc1099/convert-nemo.py#L91

**Comment by FailSpy** [comment]
Resolved now, thanks!
